Repository oskardudycz/EventSourcing.NetCore, pull requests merged in 2024-05, with the labels that each got.

#245 Changed custom IProjections like KafkaProducer, SignalRProducer, ElasticProjection to subscriptions
  Core.Marten/MartenConfig.cs
  Core.Marten/Subscriptions/MartenEventPublisher.cs
  Core.Marten/Subscriptions/MartenSubscription.cs
  Core/Commands/InMemoryCommandBus.cs
  Sample/Helpdesk.Wolverine/Helpdesk.Api/Core/Kafka/KafkaProducer.cs
  Sample/Helpdesk.Wolverine/Helpdesk.Api/Core/SignalR/SignalRProducer.cs
  Sample/Helpdesk.Wolverine/Helpdesk.Api/Program.cs
  Sample/Helpdesk/Helpdesk.Api/Core/Kafka/KafkaProducer.cs
  Sample/Helpdesk/Helpdesk.Api/Core/SignalR/SignalRProducer.cs
  Sample/Helpdesk/Helpdesk.Api/Program.cs
  Sample/MartenMeetsElastic/MartenMeetsElastic.Tests/ElasticsearchProjectionTests.cs
  Sample/MartenMeetsElastic/MartenMeetsElastic/Projections/ElasticsearchProjection.cs
  Sample/MartenMeetsElastic/MartenMeetsElastic/Projections/ElasticsearchProjectionConfig.cs
  docker-compose.ci.yml
  docker-compose.yml
Labels: enhancement, subscriptions, Marten

#256 Added example of catching breaking changes to the package with Microsoft.CodeAnalysis.PublicApiAnalyzers
  Sample/EventsVersioning/ECommerce.V1/ECommerce.V1.csproj
  Sample/EventsVersioning/ECommerce.V1/PublicAPI.Shipped.txt
  Sample/EventsVersioning/ECommerce.V1/PublicAPI.Unshipped.txt
Labels: enhancement, samples, versioning

#258 Trimmed multiple Docker Compose file into a single one with profiles
  .github/workflows/build.dotnet.yml
  EventSourcing.NetCore.sln
  README.md
  Sample/ECommerce/docker/docker-compose.yml
  Sample/Helpdesk.Wolverine/docker-compose.yml
  Sample/MeetingsManagement/docker/docker-compose.yml
  Sample/Warehouse.MinimalAPI/docker-compose.yml
  Workshops/BuildYourOwnEventStore/docker/docker-compose.yml
  Workshops/IntroductionToEventSourcing/docker-compose.yml
  docker-compose.build.yml
  docker-compose.ci.yml
  docker-compose.pg.yml
  docker-compose.yml
Labels: enhancement, CI

#263 remove redundant null suppressions
  Core.EventStoreDB/Serialization/EventStoreDBSerializer.cs
  Marten.Integration.Tests/CompositeIds/CompositeIdsTests.cs
  Marten.Integration.Tests/EventStore/Aggregate/OutOfOrder/OutOfOrderProjectionsTest.cs
  Marten.Integration.Tests/General/StoreInitializationTests.cs
  Sample/EventsVersioning/EventsVersioning.Tests/Transformations/StreamTransformations.cs
  Sample/decider/Decider.Tests/UnionTypesTests.cs
  Workshops/BuildYourOwnEventStore/02-CreateEventsTable/Exercise02CreateEventsTable.cs
  Workshops/IntroductionToEventSourcing/Solved/13-Projections.SingleStream.Idempotency/ProjectionsTests.cs
Labels: enhancement

#261 remove redundant verbatim strings
  Workshops/BuildYourOwnEventStore/08-Snapshots/Exercise08Snapshots.cs
  Workshops/BuildYourOwnEventStore/Tools/Tools/PostgresSchemaProvider.cs
Labels: enhancement

#265 remove some redundant class bodies
  Core/Aggregates/IAggregate.cs
  Core/Decider/Decider.cs
  Core/Events/IExternalEvent.cs
  Core/Events/TimeHasPassed.cs
  Core/ProcessManagers/IProcessManager.cs
  Core/ProcessManagers/ProcessManager.cs
  Core/Projections/IProjection.cs
  Marten.Integration.Tests/TestsInfrastructure/MartenTest.cs
  Sample/AsyncProjections/SmartHome.Api/Program.cs
  Sample/CRUDToCQRS/01-CRUD/ECommerce/Program.cs
  Sample/CRUDToCQRS/02-CRUDWithCQRS/ECommerce/Program.cs
  Sample/CRUDToCQRS/03-DomainGrouping/ECommerce/Program.cs
  Sample/CRUDToCQRS/04-SlimmedDomain/ECommerce/Program.cs
  Sample/CRUDToCQRS/05-ExplicitDomain/ECommerce/Program.cs
  Sample/CRUDToCQRS/06-SlicedDomain/ECommerce/Program.cs
  Sample/CRUDToCQRS/07-FlattenedLayers/ECommerce/Program.cs
  Sample/ClosingTheBooks/PointOfSales.Api/Program.cs
  Sample/ECommerce/Carts/Carts.Api/Program.cs
  Sample/ECommerce/Orders/Orders.Api/Program.cs
  Sample/ECommerce/Payments/Payments.Api/Program.cs
  Sample/ECommerce/Shipments/Shipments.Api/Program.cs
  Sample/EventStoreDB/ECommerce/Carts/Carts.Api/Program.cs
  Sample/EventStoreDB/Simple/ECommerce.Api/Program.cs
  Sample/Helpdesk.Wolverine/Helpdesk.Api.Tests/IntegrationContext.cs
  Sample/Helpdesk.Wolverine/Helpdesk.Api/Program.cs
  Sample/Helpdesk/Helpdesk.Api/Program.cs
  Sample/MeetingsManagement/MeetingsManagement.Api/Program.cs
  Sample/MeetingsManagement/MeetingsSearch.Api/Program.cs
  Sample/Tickets/Tickets.Api/Controllers/ConcertsController.cs
  Sample/Tickets/Tickets.Api/Controllers/SeatsController.cs
  Sample/Tickets/Tickets.Api/Controllers/TicketsController.cs
  Sample/Tickets/Tickets.Api/Program.cs
  Sample/Warehouse/Warehouse.Api/Program.cs
  SwaggerUi.Aspire.Hosting/SwaggerUiResource.cs
  Workshops/IntroductionToEventSourcing/08-ApplicationLogic.Marten/Program.cs
  Workshops/IntroductionToEventSourcing/09-ApplicationLogic.EventStoreDB/Program.cs
  Workshops/IntroductionToEventSourcing/10-OptimisticConcurrency.Marten/Program.cs
  Workshops/IntroductionToEventSourcing/11-OptimisticConcurrency.EventStoreDB/Program.cs
  Workshops/IntroductionToEventSourcing/Solved/08-ApplicationLogic.Marten/Program.cs
  Workshops/IntroductionToEventSourcing/Solved/09-ApplicationLogic.EventStoreDB/Program.cs
  Workshops/IntroductionToEventSourcing/Solved/10-OptimisticConcurrency.Marten/Program.cs
  Workshops/IntroductionToEventSourcing/Solved/11-OptimisticConcurrency.EventStoreDB/Program.cs
Labels: enhancement

#276 remove unecessary ToArray alloc
  Core/Aggregates/Aggregate.cs
Labels: enhancement

#277 use char overload for split
  Core.ElasticSearch/Indices/IndexNameMapper.cs
  Core.ElasticSearch/Repository/ElasticSearchExtensions.cs
  Core/Events/StreamNameMapper.cs
  Sample/Helpdesk.Wolverine/Helpdesk.Api.Tests/Incidents/Fixtures/Scenarios.cs
Labels: enhancement

#270 thoughts on global usings?
  Core/Aggregates/IAggregate.cs
  Core/BackgroundWorkers/BackgroundWorker.cs
  Core/Commands/CommandForwarder.cs
  Core/Commands/CommandHandlerActivity.cs
  Core/Commands/CommandHandlerMetrics.cs
  Core/Commands/Config.cs
  Core/Commands/InMemoryCommandBus.cs
  Core/Config.cs
  Core/Configuration/ConfigurationExtensions.cs
  Core/Events/Config.cs
  Core/Events/EventBus.cs
  Core/Events/EventEnvelope.cs
  Core/Events/EventTypeMapper.cs
  Core/Events/StreamNameMapper.cs
  Core/GlobalUsings.cs
  Core/OpenTelemetry/ActivityScope.cs
  Core/OpenTelemetry/ActivitySourceProvider.cs
  Core/OpenTelemetry/Serialization/PropagationContextJsonConverter.cs
  Core/OpenTelemetry/TelemetryExtensions.cs
  Core/OpenTelemetry/TelemetryPropagator.cs
  Core/ProcessManagers/IProcessManager.cs
  Core/ProcessManagers/ProcessManager.cs
  Core/Queries/Config.cs
  Core/Queries/QueryBus.cs
  Core/Reflection/ObjectFactory.cs
  Core/Reflection/TypeConverter.cs
  Core/Reflection/TypeProvider.cs
  Core/Validation/ValidationExtensions.cs
Labels: enhancement

#280 Added Nginx configuration with multiple replicas for Helpdesk sample
  Sample/Helpdesk/Helpdesk.Api/.dockerignore
  Sample/Helpdesk/Helpdesk.Api/Dockerfile
  Sample/Helpdesk/Helpdesk.Api/Incidents/GetCustomerIncidentsSummary/IncidentSummary.cs
  Sample/Helpdesk/Helpdesk.Api/Program.cs
  Sample/Helpdesk/Helpdesk.Api/docker-compose.yml
  Sample/Helpdesk/Helpdesk.Api/nginx.conf
Labels: enhancement, samples

#282 Simplfied AsyncEnumerable batching by using OpenExtension package
  Core.EventStoreDB/Subscriptions/EventStoreDBSubscriptionToAll.cs
  Core.Testing/TestWebApplicationFactory.cs
  Core/Extensions/AsyncEnumerableExtensions.cs
  Sample/ECommerce/Orders/Orders/Config.cs
Labels: enhancement, refactoring
